version: "3"

services:
# database service
  database:
    image : mysql
    container_name : innoscripta-mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: innoscripta
      MYSQL_ROOT_PASSWORD: password

# backend service
  backend:
    container_name: dlr
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www

# frontend service
  frontend:
    build: ./frontend
    image: innoscripta-frontend
    container_name: innoscripta-frontend
    restart: always
    ports:
      - 3000:3000
    networks:
      - innoscripta-network
    depends_on:
      - backend

networks:
  innoscripta-network:
    driver: bridge
