version: "3"

services:
  backend:
    build: ./backend
    container_name: innoscripta-backend
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/var/www
    networks:
      - innoscripta-network

networks:
  innoscripta-network:
    driver: bridge